const Carddata = [
    {
        id: 1,
    image: "../../image/1.jpg",
    name: "Grand Court SE Shoes ",
    category: "Fashion",
    price: 25,
    description: " The Best Fashion shoes",
}, 

{
    id: 2,
    image: "../../image/2.jpg",
    name: "Grand Court SE Shoes ",
    category: "Fashion",
    price: 25,
    description: " The Best Fashion shoes",
}, 
{
    id: 3,
    image: "../../image/3.jpg",
    name: "Nike Air  Jordan III",
    category: "Fashion",
    price: " RS. 2500",
    description: " The Best Fashion shoes",
},
 {
    id: 4,
    image: "../../image/4.jpg",
    name: "Nike Air  Jordan Courtside 23 white",
    category: "Fashion",
    price: 25,
    description: " The Best Fashion shoes",
}, 
{
    id: 5,
    image: "../../image/5.jpg",
    name: "Nike Air  Jordan Courtside 23  Black",
    category: "Fashion",
    price: 25,
    description: " The Best Fashion shoes",
},
{
    id: 6,
    image: "../../image/6.jpg",
    name: "Nike Air  Jordan Courtside 23  Black",
    category: "Fashion",
    price: 25,
    description: " The Best Fashion shoes",
},
{
    id: 7,
    image: "../../image/7.jpg",
    name: "Nike Air  Jordan Courtside 23  Black",
    category: "Fashion",
    price: 25,
    description: " The Best Fashion shoes",
},
{
    id: 8,
    image: "../../image/8.jpg",
    name: "Nike Air  Jordan Courtside 23  Black",
    category: "Fashion",
    price: 25,
    description: " The Best Fashion shoes",
},
{
    id: 9,
    image: "../../image/9.jpg",
    name: "Nike Air  Jordan Courtside 23  Black",
    category: "Fashion",
    price: 25,
    description: " The Best Fashion shoes",
},
{
    id: 10,
    image: "../../image/10.jpg",
    name: "Nike Air  Jordan Courtside 23  Black",
    category: "Fashion",
    price: 25,
    description: " The Best Fashion shoes",
},
{
    id: 11,
    image: "../../image/11.jpg",
    name: "Nike Air  Jordan Courtside 23  Black",
    category: "Fashion",
    price: 25,
    description: " The Best Fashion shoes",
},
{
    id: 12,
    image: "../../image/12.jpg",
    name: "Nike Air  Jordan Courtside 23  Black",
    category: "Fashion",
    price: 25,
    description: " The Best Fashion shoes",
},
{
    id: 13,
    image: "../../image/13.jpg",
    name: "Nike Air  Jordan Courtside 23  Black",
    category: "Fashion",
    price: 25,
    description: " The Best Fashion shoes",
},
{
    id: 14,
    image: "../../image/14.jpg",
    name: "Nike Air  Jordan Courtside 23  Black",
    category: "Fashion",
    price: 25,
    description: " The Best Fashion shoes",
},
{
    id: 15,
    image: "../../image/15.jpg",
    name: "Nike Air  Jordan Courtside 23  Black",
    category: "Fashion",
    price: 25,
    description: " The Best Fashion shoes",
},
{
    id: 16,
    image: "../../image/16.jpg",
    name: "Nike Air  Jordan Courtside 23  Black",
    category: "Fashion",
    price: 25,
    description: " The Best Fashion shoes",
}
]
export default Carddata;